jobs:
  install:
    executor:
      name: node/default
      tag: "12.18"
    parameters:
      before_install:
        default:
          - checkout
        description: |
          Steps to be executed before restoring cache and running install. Default is to run 'checkout' command.
        type: steps
  test:
    executor:
      name: node/default
      tag: "12.18"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
  build:
    executor:
      name: node/default
      tag: "12.18"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build

version: 2.1
orbs:
  node: circleci/node@4.0.0
workflows:
  catalog:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
            - install
